# Site Settings
site: Sarah Schumacher

# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

# Defaults for Layouts
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Markdown and Syntax Highlighting
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass Configuration
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination Configuration
pagination:
  enabled: true
  per_page: 10
  paginate_path: "/blog/page:num/"
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Custom Gallery Types (Optional)
gallery_types:
  carousel: Carousel
  grid: Grid

# Grid Column Options (Optional)
grid_columns:
  two: Two
  three: Three
  four: Four
