name: Update Dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository with node 20 support
      - name: Checkout code
        uses: actions/checkout@v3
        env:
          NODE_VERSION: 20

      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Adjust this version according to your project

      # Install Bundler
      - name: Install Bundler
        run: gem install bundler

      # Update Dependencies
      - name: Update Dependencies
        run: bundle update

      # Build Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build

      # Optional: Test with HTML Proofer
      - name: Test with HTML Proofer
        run: bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
