name: Update Dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5 # Using the correct Ruby version

      # Remove any outdated Bundler versions
      - name: Remove old Bundler
        run: gem uninstall bundler -v 1.16.1

      # Install the latest Bundler version
      - name: Install Bundler
        run: gem install bundler

      # Update Dependencies
      - name: Update Dependencies
        run: bundle update

      # Build Jekyll site with trace logging for debugging
      - name: Build Jekyll site
        run: bundle exec jekyll build --trace
